-- Phase 2: replace mock tables with raw mirror tables + transform views, and
-- lock RLS to authenticated @fitelo.co users.
-- Run this whole file in the Supabase SQL Editor.
-- After running, the dashboard is empty until the first sync populates raw_*.

-- ---------- Safe-cast helpers (never error on a bad cell) ----------
create or replace function safe_numeric(t text) returns numeric language plpgsql immutable as $$
begin return nullif(regexp_replace(coalesce(t,''),'[^0-9.\-]','','g'),'')::numeric;
exception when others then return null; end; $$;

create or replace function safe_bigint(t text) returns bigint language plpgsql immutable as $$
begin return nullif(regexp_replace(coalesce(t,''),'[^0-9]','','g'),'')::bigint;
exception when others then return null; end; $$;

create or replace function safe_date(t text) returns date language plpgsql immutable as $$
begin return nullif(trim(coalesce(t,'')),'')::date;
exception when others then return null; end; $$;

-- ---------- Out with the mock (drop whether it's a table or a view) ----------
do $$
declare obj text;
begin
  foreach obj in array array['csat','sales','clients','coaches'] loop
    begin
      execute format('drop table if exists %I cascade', obj);
    exception when wrong_object_type then
      execute format('drop view if exists %I cascade', obj);
    end;
  end loop;
end $$;

-- ---------- Raw mirror tables (all text; populated by the sync) ----------
create table if not exists raw_team (
  id bigint generated by default as identity primary key,
  name text, leader text, designation text,
  synced_at timestamptz not null default now()
);

create table if not exists raw_clients (
  id bigint generated by default as identity primary key,
  customer_code text, name text, state text, age text, gender text, height text, goals text,
  current_dietitian_name text, current_exercise_coach text, current_plan text,
  current_plan_start_date text, current_plan_end_date text, plan_duration text, remaining_days text,
  first_plan text, first_plan_duration text, first_plan_start_date text, first_plan_end_date text,
  number_of_times_plan_purchased text, first_waist_log text, latest_waist_log text,
  waist_log_before_15_days_interval text, total_waist_loss text, waist_loss_in_last_15_days text,
  first_weight_log text, latest_weight_log text, current_month_first_weight text,
  weight_log_within_interval_15_days text, total_weight_loss text, weight_loss_in_last_15_days text,
  avg_rating text, latest_rating text, latest_csat_date text, coach_consultations text,
  synced_at timestamptz not null default now()
);

create table if not exists raw_csat (
  id bigint generated by default as identity primary key,
  rating_date text, code text, state text, category text, coach_name text,
  rating text, week text, client_name text, plan_name text,
  synced_at timestamptz not null default now()
);

create table if not exists raw_overall_sales (
  id bigint generated by default as identity primary key,
  cutomerid text, customername text, planname text, previousplanname text,
  currentdietitian text, currentexercisecoach text, ordertype text, dietitiancoach text,
  exercisecoach text, type text, saledate text, amount text, saletypewithextension text,
  synced_at timestamptz not null default now()
);

-- ---------- RLS: only signed-in @fitelo.co users can read raw tables ----------
do $$
declare t text;
begin
  foreach t in array array['raw_team','raw_clients','raw_csat','raw_overall_sales'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "fitelo read" on %I', t);
    execute format($p$create policy "fitelo read" on %I for select to authenticated
                      using ((auth.jwt() ->> 'email') like '%%@fitelo.co')$p$, t);
    execute format('grant select on %I to authenticated', t);
  end loop;
end $$;

-- ---------- Transform views (security_invoker => caller's RLS applies) ----------
create view coaches with (security_invoker = on) as
with names as (
  select lower(trim(name)) k, name orig from raw_team where coalesce(trim(name),'') <> ''
  union all select lower(trim(current_exercise_coach)), current_exercise_coach from raw_clients where coalesce(trim(current_exercise_coach),'') <> ''
  union all select lower(trim(current_dietitian_name)), current_dietitian_name from raw_clients where coalesce(trim(current_dietitian_name),'') <> ''
  union all select lower(trim(coach_name)), coach_name from raw_csat where coalesce(trim(coach_name),'') <> ''
  union all select lower(trim(currentexercisecoach)), currentexercisecoach from raw_overall_sales where coalesce(trim(currentexercisecoach),'') <> ''
),
distinct_names as (select k, min(orig) name from names group by k),
ranked as (select k, name, dense_rank() over (order by k) id from distinct_names),
team as (select distinct lower(trim(name)) k, designation from raw_team)
select r.id, r.name, t.designation as role, t.designation as team, 'active'::text as status, r.k as name_key
from ranked r left join team t on t.k = r.k;

create view clients with (security_invoker = on) as
select
  safe_bigint(c.customer_code) as id,
  c.name,
  co.id as coach_id,
  c.current_plan as plan,
  lower(nullif(trim(c.state),'')) as status,
  safe_date(c.current_plan_start_date) as start_date,
  safe_date(c.current_plan_end_date) as end_date,
  safe_numeric(c.total_weight_loss) as weight_lost_kg
from raw_clients c
left join coaches co on co.name_key = lower(trim(c.current_exercise_coach));

create view sales with (security_invoker = on) as
select
  row_number() over () as id,
  safe_date(s.saledate) as sale_date,
  safe_bigint(s.cutomerid) as client_id,
  co.id as coach_id,
  s.planname as plan_name,
  coalesce(safe_numeric(s.amount), 0) as amount,
  lower(nullif(trim(s.saletypewithextension),'')) as sale_type
from raw_overall_sales s
left join coaches co on co.name_key = lower(trim(s.currentexercisecoach));

create view csat with (security_invoker = on) as
select
  row_number() over () as id,
  safe_date(c.rating_date) as rating_date,
  safe_bigint(c.code) as client_id,
  co.id as coach_id,
  safe_numeric(c.rating) as rating,
  lower(nullif(trim(c.category),'')) as category
from raw_csat c
left join coaches co on co.name_key = lower(trim(c.coach_name))
where coalesce(safe_numeric(c.rating), 0) > 0;   -- exclude 0 / unrated

grant select on coaches, clients, sales, csat to authenticated;
