-- 0005: Coaches now come from 3 dedicated sheet tabs (PT / Basic / Dietitian),
-- each tagged with a `type`. Replaces the previous "derive coach names from the
-- Clients/Sales/CSAT data" approach. Names use the same "Name ECODE" format, so
-- the existing name-based joins for per-coach revenue/CSAT keep working.

-- 1) Raw tables mirroring column A (the coach name) of each coach tab.
create table if not exists raw_pt_coaches (
  id bigint generated by default as identity primary key,
  coach text,
  synced_at timestamptz not null default now()
);
create table if not exists raw_basic_coaches (
  id bigint generated by default as identity primary key,
  core_coaches text,
  synced_at timestamptz not null default now()
);
create table if not exists raw_dietitians (
  id bigint generated by default as identity primary key,
  dietitian text,
  synced_at timestamptz not null default now()
);

-- RLS: only signed-in @fitelo.co users can read the raw tables.
do $$
declare t text;
begin
  foreach t in array array['raw_pt_coaches','raw_basic_coaches','raw_dietitians'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "fitelo read" on %I', t);
    execute format($p$create policy "fitelo read" on %I for select to authenticated
                      using ((auth.jwt() ->> 'email') like '%%@fitelo.co')$p$, t);
    execute format('grant select on %I to authenticated', t);
  end loop;
end $$;

-- 2) Rebuild the materialized coach map from the 3 sheets, tagged by type.
drop view if exists csat, sales, clients, coaches cascade;
drop materialized view if exists mv_coaches cascade;

create materialized view mv_coaches as
with src as (
  select 'pt'::text        as type, coach        as nm from raw_pt_coaches
  union all
  select 'basic'::text     as type, core_coaches as nm from raw_basic_coaches
  union all
  select 'dietitian'::text as type, dietitian    as nm from raw_dietitians
),
clean as (
  select lower(trim(nm)) as name_key, trim(nm) as name, type
  from src
  where coalesce(trim(nm), '') <> ''
    and trim(nm) not like '//%'   -- skip note/comment rows like "//ANU and Pawani"
),
distinct_coaches as (
  -- one row per coach; if a name appears under >1 type, pick one deterministically
  select name_key, min(name) as name, min(type) as type
  from clean
  group by name_key
),
ranked as (
  select name_key, name, type,
         dense_rank() over (order by name_key)::bigint as id
  from distinct_coaches
)
select id, name, type as role, type as team, 'active'::text as status, name_key, type
from ranked;

create unique index mv_coaches_id_idx on mv_coaches (id);
create index mv_coaches_name_key_idx on mv_coaches (name_key);
grant select on mv_coaches to authenticated;

-- 3) Typed views over the raw data (same shape as before; coaches now exposes `type`).
create view coaches with (security_invoker = on) as
  select id, name, role, team, status, name_key, type from mv_coaches
  where (auth.jwt() ->> 'email') like '%@fitelo.co';

create view clients with (security_invoker = on) as
select
  safe_bigint(c.customer_code) as id,
  c.name,
  co.id as coach_id,
  c.current_plan as plan,
  lower(nullif(trim(c.state),'')) as status,
  safe_date(c.current_plan_start_date) as start_date,
  safe_date(c.current_plan_end_date) as end_date,
  safe_numeric(c.total_weight_loss) as weight_lost_kg
from raw_clients c
left join mv_coaches co on co.name_key = lower(trim(c.current_exercise_coach));

create view sales with (security_invoker = on) as
select
  row_number() over () as id,
  safe_date(s.saledate) as sale_date,
  safe_bigint(s.cutomerid) as client_id,
  co.id as coach_id,
  s.planname as plan_name,
  coalesce(safe_numeric(s.amount), 0) as amount,
  lower(nullif(trim(s.saletypewithextension),'')) as sale_type
from raw_overall_sales s
left join mv_coaches co on co.name_key = lower(trim(s.currentexercisecoach));

create view csat with (security_invoker = on) as
select
  row_number() over () as id,
  safe_date(c.rating_date) as rating_date,
  safe_bigint(c.code) as client_id,
  co.id as coach_id,
  safe_numeric(c.rating) as rating,
  lower(nullif(trim(c.category),'')) as category
from raw_csat c
left join mv_coaches co on co.name_key = lower(trim(c.coach_name))
where coalesce(safe_numeric(c.rating), 0) > 0;

grant select on coaches, clients, sales, csat to authenticated;

-- refresh_dashboard() still just refreshes mv_coaches; re-created for clarity.
create or replace function refresh_dashboard() returns void
language plpgsql security definer as $$
begin
  refresh materialized view mv_coaches;
end $$;
grant execute on function refresh_dashboard() to authenticated, service_role;
