-- 0006: "Sales by LEANR Team" monthly numbers, parsed from the Sales_LeanrTeam
-- pivot sheet (one row per month). The sync unpivots that sheet into this table.

create table if not exists raw_sales_leanr_team (
  id bigint generated by default as identity primary key,
  month text,            -- 'YYYY-MM'
  extention integer,
  renew integer,
  reactivation integer,
  reference integer,
  total integer,
  synced_at timestamptz not null default now()
);

-- RLS: only signed-in @fitelo.co users can read.
alter table raw_sales_leanr_team enable row level security;
drop policy if exists "fitelo read" on raw_sales_leanr_team;
create policy "fitelo read" on raw_sales_leanr_team for select to authenticated
  using ((auth.jwt() ->> 'email') like '%@fitelo.co');
grant select on raw_sales_leanr_team to authenticated;
