-- 0008: Per-coach current-month sales from the "Leaner_Team_Sales" tab.
-- Layout: column A = type label ('Dietitian' | 'Basic Coach' | 'PT Coach'),
-- column B = coach name ('Name ECODE'), column C = this month's sale value (₹).
-- Rows are grouped by type with blank separators; the sync drops the blanks.
-- Powers the "top performers" widgets on the Overview and Sales pages.

create table if not exists raw_leaner_team_sales (
  id bigint generated by default as identity primary key,
  coach_type text,   -- raw label: 'Dietitian' | 'Basic Coach' | 'PT Coach'
  coach text,        -- 'Name ECODE'
  amount numeric,    -- sale value for the current month
  synced_at timestamptz not null default now()
);

-- RLS: only signed-in @fitelo.co users can read.
alter table raw_leaner_team_sales enable row level security;
drop policy if exists "fitelo read" on raw_leaner_team_sales;
create policy "fitelo read" on raw_leaner_team_sales for select to authenticated
  using ((auth.jwt() ->> 'email') like '%@fitelo.co');
grant select on raw_leaner_team_sales to authenticated;

-- Typed view: normalize the type label to the same codes the coach roster uses
-- ('pt' | 'basic' | 'dietitian') and expose a clean numeric amount.
create or replace view coach_month_sales with (security_invoker = on) as
select
  trim(coach) as coach,
  case
    when lower(coach_type) like 'pt%'    then 'pt'
    when lower(coach_type) like 'basic%' then 'basic'
    when lower(coach_type) like 'diet%'  then 'dietitian'
    else lower(trim(coach_type))
  end as type,
  coalesce(amount, 0) as amount
from raw_leaner_team_sales
where coalesce(trim(coach), '') <> '';

grant select on coach_month_sales to authenticated;
