-- 0009: per-coach renewal/extension opportunity data, from the
-- "raw_data_coaches_opportunity" tab. The sync reads that tab BY COLUMN POSITION
-- (several of its headers are blank and would collide under the generic mirror)
-- and writes the few columns we need into this clean table.

create table if not exists raw_coach_opportunity (
  id bigint generated by default as identity primary key,
  dietitian text,        -- col G: dietitian coach ('Name ECODE')
  exercise_coach text,   -- col I: exercise coach ('Name ECODE')
  renewal_opp text,      -- col J: 'YES' | 'NO'
  extension_opp text,    -- col K: 'YES' | 'NO'
  purchase_w text,       -- col W: latest purchase type (--, Product, Miscellanous, ...)
  purchase_x text,       -- col X: secondary purchase type
  synced_at timestamptz not null default now()
);

-- RLS: only signed-in @fitelo.co users can read.
alter table raw_coach_opportunity enable row level security;
drop policy if exists "fitelo read" on raw_coach_opportunity;
create policy "fitelo read" on raw_coach_opportunity for select to authenticated
  using ((auth.jwt() ->> 'email') like '%@fitelo.co');
grant select on raw_coach_opportunity to authenticated;
