-- 0011: coach -> team mapping from the "Team Structure" tab, used to roll up
-- renewal opportunities per team on the Opportunity page. The sync reads the
-- horizontal team blocks (team name in row 3, coaches listed below each column).

create table if not exists raw_team_structure (
  id bigint generated by default as identity primary key,
  coach text,   -- 'Name ECODE'
  team text,    -- e.g. 'Team Shruti', 'ICs'
  synced_at timestamptz not null default now()
);

-- RLS: only signed-in @fitelo.co users can read.
alter table raw_team_structure enable row level security;
drop policy if exists "fitelo read" on raw_team_structure;
create policy "fitelo read" on raw_team_structure for select to authenticated
  using ((auth.jwt() ->> 'email') like '%@fitelo.co');
grant select on raw_team_structure to authenticated;
