-- 0012: per-coach sales targets from the "Coach Wise Target" tab. The sync reads
-- that tab BY COLUMN POSITION (it has blank spacer columns between groups and
-- messy/duplicate headers that would collide under the generic mirror) and writes
-- the team, coach, and the four target amounts (+ the total) into this table.
-- Rolled up per team on the Sales Target page, with expandable per-coach rows.

create table if not exists raw_coach_targets (
  id bigint generated by default as identity primary key,
  team text,                             -- col A: e.g. 'Team Shruti', 'ICs'
  category text,                         -- col B: coach category
  coach text,                            -- col C: 'Name ECODE'
  total_target double precision,         -- col D: total target (₹) = sum of the four below
  renewal_target double precision,       -- col H
  extension_target double precision,     -- col M
  referral_target double precision,      -- col R
  reactivation_target double precision,  -- col U
  synced_at timestamptz not null default now()
);

-- RLS: only signed-in @fitelo.co users can read.
alter table raw_coach_targets enable row level security;
drop policy if exists "fitelo read" on raw_coach_targets;
create policy "fitelo read" on raw_coach_targets for select to authenticated
  using ((auth.jwt() ->> 'email') like '%@fitelo.co');
grant select on raw_coach_targets to authenticated;
